"""
✨ `City_KeyOutput` returns the primary key fields of table type `City`.

It has the same format as `City_Key`, but is only used as mutation return value.
"""
scalar City_KeyOutput
"""
✨ `Cuisine_KeyOutput` returns the primary key fields of table type `Cuisine`.

It has the same format as `Cuisine_Key`, but is only used as mutation return value.
"""
scalar Cuisine_KeyOutput
"""
✨ `EstablishmentType_KeyOutput` returns the primary key fields of table type `EstablishmentType`.

It has the same format as `EstablishmentType_Key`, but is only used as mutation return value.
"""
scalar EstablishmentType_KeyOutput
"""
✨ `Favorite_KeyOutput` returns the primary key fields of table type `Favorite`.

It has the same format as `Favorite_Key`, but is only used as mutation return value.
"""
scalar Favorite_KeyOutput
"""
✨ `Restaurant_KeyOutput` returns the primary key fields of table type `Restaurant`.

It has the same format as `Restaurant_Key`, but is only used as mutation return value.
"""
scalar Restaurant_KeyOutput
"""
✨ `RestaurantCuisine_KeyOutput` returns the primary key fields of table type `RestaurantCuisine`.

It has the same format as `RestaurantCuisine_Key`, but is only used as mutation return value.
"""
scalar RestaurantCuisine_KeyOutput
"""
✨ `RestaurantType_KeyOutput` returns the primary key fields of table type `RestaurantType`.

It has the same format as `RestaurantType_Key`, but is only used as mutation return value.
"""
scalar RestaurantType_KeyOutput
"""
✨ `Review_KeyOutput` returns the primary key fields of table type `Review`.

It has the same format as `Review_Key`, but is only used as mutation return value.
"""
scalar Review_KeyOutput
"""
✨ `Schedule_KeyOutput` returns the primary key fields of table type `Schedule`.

It has the same format as `Schedule_Key`, but is only used as mutation return value.
"""
scalar Schedule_KeyOutput
"""
✨ `User_KeyOutput` returns the primary key fields of table type `User`.

It has the same format as `User_Key`, but is only used as mutation return value.
"""
scalar User_KeyOutput
"""
✨ Generated data input type for table 'City'. It includes all necessary fields for creating or upserting rows into table.
"""
input City_Data {
  """
  ✨ Generated from Field `City`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `City`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `City`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `City`.`name` of type `String!`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `City`.`restaurants_on_city` of type `[Restaurant!]!`
  """
  restaurants_on_city: [Restaurant_Data!]
}
"""
✨ Generated filter input type for table 'City'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input City_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [City_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: City_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [City_Filter!]
  """
  ✨ Generated from Field `City`.`id` of type `String!`
  """
  id: String_Filter
  """
  ✨ Generated from Field `City`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `City`.`restaurants_on_city` of type `[Restaurant!]!`
  """
  restaurants_on_city: Restaurant_ListFilter
}
"""
✨ Generated first-row input type for table 'City'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input City_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [City_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: City_Filter
}
"""
✨ Generated having input type for table 'City'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input City_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [City_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: City_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [City_Having!]
  """
  ✨ Generated from Field `City`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `City`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `City`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
}
"""
✨ Generated key input type for table 'City'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input City_Key {
  """
  ✨ Generated from Field `City`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `City`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'City'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input City_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: City_Filter
}
"""
✨ Generated order input type for table 'City'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input City_Order {
  """
  ✨ Generated from Field `City`.`id` of type `String!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `City`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `City`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `City`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `City`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
}
"""
✨ Generated data input type for table 'Cuisine'. It includes all necessary fields for creating or upserting rows into table.
"""
input Cuisine_Data {
  """
  ✨ Generated from Field `Cuisine`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Cuisine`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Cuisine`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Cuisine`.`name` of type `String!`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Cuisine`.`restaurantCuisines_on_cuisine` of type `[RestaurantCuisine!]!`
  """
  restaurantCuisines_on_cuisine: [RestaurantCuisine_Data!]
}
"""
✨ Generated filter input type for table 'Cuisine'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Cuisine_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Cuisine_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Cuisine_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Cuisine_Filter!]
  """
  ✨ Generated from Field `Cuisine`.`id` of type `String!`
  """
  id: String_Filter
  """
  ✨ Generated from Field `Cuisine`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Cuisine`.`restaurantCuisines_on_cuisine` of type `[RestaurantCuisine!]!`
  """
  restaurantCuisines_on_cuisine: RestaurantCuisine_ListFilter
  """
  ✨ Generated from Field `Cuisine`.`restaurants_via_RestaurantCuisine` of type `[Restaurant!]!`
  """
  restaurants_via_RestaurantCuisine: Restaurant_ListFilter
}
"""
✨ Generated first-row input type for table 'Cuisine'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Cuisine_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Cuisine_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Cuisine_Filter
}
"""
✨ Generated having input type for table 'Cuisine'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Cuisine_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Cuisine_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Cuisine_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Cuisine_Having!]
  """
  ✨ Generated from Field `Cuisine`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Cuisine`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Cuisine`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
}
"""
✨ Generated key input type for table 'Cuisine'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Cuisine_Key {
  """
  ✨ Generated from Field `Cuisine`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Cuisine`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Cuisine'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Cuisine_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Cuisine_Filter
}
"""
✨ Generated order input type for table 'Cuisine'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Cuisine_Order {
  """
  ✨ Generated from Field `Cuisine`.`id` of type `String!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Cuisine`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Cuisine`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Cuisine`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Cuisine`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
}
"""
✨ Generated data input type for table 'EstablishmentType'. It includes all necessary fields for creating or upserting rows into table.
"""
input EstablishmentType_Data {
  """
  ✨ Generated from Field `EstablishmentType`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `EstablishmentType`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `EstablishmentType`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `EstablishmentType`.`name` of type `String!`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `EstablishmentType`.`restaurantTypes_on_type` of type `[RestaurantType!]!`
  """
  restaurantTypes_on_type: [RestaurantType_Data!]
}
"""
✨ Generated filter input type for table 'EstablishmentType'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input EstablishmentType_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [EstablishmentType_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: EstablishmentType_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [EstablishmentType_Filter!]
  """
  ✨ Generated from Field `EstablishmentType`.`id` of type `String!`
  """
  id: String_Filter
  """
  ✨ Generated from Field `EstablishmentType`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `EstablishmentType`.`restaurantTypes_on_type` of type `[RestaurantType!]!`
  """
  restaurantTypes_on_type: RestaurantType_ListFilter
  """
  ✨ Generated from Field `EstablishmentType`.`restaurants_via_RestaurantType` of type `[Restaurant!]!`
  """
  restaurants_via_RestaurantType: Restaurant_ListFilter
}
"""
✨ Generated first-row input type for table 'EstablishmentType'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input EstablishmentType_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [EstablishmentType_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: EstablishmentType_Filter
}
"""
✨ Generated having input type for table 'EstablishmentType'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input EstablishmentType_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [EstablishmentType_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: EstablishmentType_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [EstablishmentType_Having!]
  """
  ✨ Generated from Field `EstablishmentType`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `EstablishmentType`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `EstablishmentType`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
}
"""
✨ Generated key input type for table 'EstablishmentType'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input EstablishmentType_Key {
  """
  ✨ Generated from Field `EstablishmentType`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `EstablishmentType`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'EstablishmentType'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input EstablishmentType_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: EstablishmentType_Filter
}
"""
✨ Generated order input type for table 'EstablishmentType'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input EstablishmentType_Order {
  """
  ✨ Generated from Field `EstablishmentType`.`id` of type `String!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `EstablishmentType`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `EstablishmentType`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `EstablishmentType`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `EstablishmentType`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
}
"""
✨ Generated data input type for table 'Favorite'. It includes all necessary fields for creating or upserting rows into table.
"""
input Favorite_Data {
  """
  ✨ Generated from Field `Favorite`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Favorite`.`userId` of type `String!`)
  """
  userId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Favorite`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `Favorite`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Favorite`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Favorite`.`user` of type `User!`
  """
  user: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Favorite`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Favorite`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Favorite`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Favorite`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Favorite'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Favorite_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Favorite_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Favorite_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Favorite_Filter!]
  """
  ✨ Generated from Field `Favorite`.`userId` of type `String!`
  """
  userId: String_Filter
  """
  ✨ Generated from Field `Favorite`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID_Filter
  """
  ✨ Generated from Field `Favorite`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Filter
  """
  ✨ Generated from Field `Favorite`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Favorite`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'Favorite'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Favorite_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Favorite_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Favorite_Filter
}
"""
✨ Generated having input type for table 'Favorite'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Favorite_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Favorite_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Favorite_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Favorite_Having!]
  """
  ✨ Generated from Field `Favorite`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Favorite`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Favorite`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: Int_Filter
  """
  ✨ Generated from Field `Favorite`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `Favorite`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Favorite`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Favorite'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Favorite_Key {
  """
  ✨ Generated from Field `Favorite`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Favorite`.`userId` of type `String!`)
  """
  userId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Favorite`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `Favorite`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Favorite'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Favorite_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Favorite_Filter
}
"""
✨ Generated order input type for table 'Favorite'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Favorite_Order {
  """
  ✨ Generated from Field `Favorite`.`userId` of type `String!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Favorite`.`restaurantId` of type `UUID!`
  """
  restaurantId: OrderDirection
  """
  ✨ Generated from Field `Favorite`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Order
  """
  ✨ Generated from Field `Favorite`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Favorite`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Favorite`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Favorite`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Favorite`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: OrderDirection
  """
  ✨ Generated from Field `Favorite`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `Favorite`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Favorite`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Restaurant'. It includes all necessary fields for creating or upserting rows into table.
"""
input Restaurant_Data {
  """
  ✨ Generated from Field `Restaurant`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Restaurant`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`cityId` of type `String!`
  """
  cityId: String
  """
  ✨ `_expr` server value variant of `cityId` (✨ Generated from Field `Restaurant`.`cityId` of type `String!`)
  """
  cityId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`city` of type `City!`
  """
  city: City_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`address` of type `String!`
  """
  address: String
  """
  ✨ `_expr` server value variant of `address` (✨ Generated from Field `Restaurant`.`address` of type `String!`)
  """
  address_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Restaurant`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Restaurant`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Restaurant`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Restaurant`.`description` of type `String`)
  """
  description_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`imageUrl` of type `String!`
  """
  imageUrl: String
  """
  ✨ `_expr` server value variant of `imageUrl` (✨ Generated from Field `Restaurant`.`imageUrl` of type `String!`)
  """
  imageUrl_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`latitude` of type `Float!`
  """
  latitude: Float
  """
  ✨ `_expr` server value variant of `latitude` (✨ Generated from Field `Restaurant`.`latitude` of type `Float!`)
  """
  latitude_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `latitude` (✨ Generated from Field `Restaurant`.`latitude` of type `Float!`)
  """
  latitude_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`longitude` of type `Float!`
  """
  longitude: Float
  """
  ✨ `_expr` server value variant of `longitude` (✨ Generated from Field `Restaurant`.`longitude` of type `Float!`)
  """
  longitude_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `longitude` (✨ Generated from Field `Restaurant`.`longitude` of type `Float!`)
  """
  longitude_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Restaurant`.`name` of type `String!`)
  """
  name_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`phone` of type `String`
  """
  phone: String
  """
  ✨ `_expr` server value variant of `phone` (✨ Generated from Field `Restaurant`.`phone` of type `String`)
  """
  phone_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`status` of type `String!`
  """
  status: String
  """
  ✨ `_expr` server value variant of `status` (✨ Generated from Field `Restaurant`.`status` of type `String!`)
  """
  status_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `Restaurant`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `Restaurant`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `Restaurant`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`website` of type `String`
  """
  website: String
  """
  ✨ `_expr` server value variant of `website` (✨ Generated from Field `Restaurant`.`website` of type `String`)
  """
  website_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Restaurant`.`favorites_on_restaurant` of type `[Favorite!]!`
  """
  favorites_on_restaurant: [Favorite_Data!]
  """
  ✨ Generated from Field `Restaurant`.`restaurantCuisines_on_restaurant` of type `[RestaurantCuisine!]!`
  """
  restaurantCuisines_on_restaurant: [RestaurantCuisine_Data!]
  """
  ✨ Generated from Field `Restaurant`.`restaurantTypes_on_restaurant` of type `[RestaurantType!]!`
  """
  restaurantTypes_on_restaurant: [RestaurantType_Data!]
  """
  ✨ Generated from Field `Restaurant`.`reviews_on_restaurant` of type `[Review!]!`
  """
  reviews_on_restaurant: [Review_Data!]
  """
  ✨ Generated from Field `Restaurant`.`schedules_on_restaurant` of type `[Schedule!]!`
  """
  schedules_on_restaurant: [Schedule_Data!]
}
"""
✨ Generated filter input type for table 'Restaurant'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Restaurant_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Restaurant_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Restaurant_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Restaurant_Filter!]
  """
  ✨ Generated from Field `Restaurant`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Restaurant`.`cityId` of type `String!`
  """
  cityId: String_Filter
  """
  ✨ Generated from Field `Restaurant`.`city` of type `City!`
  """
  city: City_Filter
  """
  ✨ Generated from Field `Restaurant`.`address` of type `String!`
  """
  address: String_Filter
  """
  ✨ Generated from Field `Restaurant`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Restaurant`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Restaurant`.`imageUrl` of type `String!`
  """
  imageUrl: String_Filter
  """
  ✨ Generated from Field `Restaurant`.`latitude` of type `Float!`
  """
  latitude: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`longitude` of type `Float!`
  """
  longitude: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Restaurant`.`phone` of type `String`
  """
  phone: String_Filter
  """
  ✨ Generated from Field `Restaurant`.`status` of type `String!`
  """
  status: String_Filter
  """
  ✨ Generated from Field `Restaurant`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `Restaurant`.`website` of type `String`
  """
  website: String_Filter
  """
  ✨ Generated from Field `Restaurant`.`favorites_on_restaurant` of type `[Favorite!]!`
  """
  favorites_on_restaurant: Favorite_ListFilter
  """
  ✨ Generated from Field `Restaurant`.`restaurantCuisines_on_restaurant` of type `[RestaurantCuisine!]!`
  """
  restaurantCuisines_on_restaurant: RestaurantCuisine_ListFilter
  """
  ✨ Generated from Field `Restaurant`.`restaurantTypes_on_restaurant` of type `[RestaurantType!]!`
  """
  restaurantTypes_on_restaurant: RestaurantType_ListFilter
  """
  ✨ Generated from Field `Restaurant`.`reviews_on_restaurant` of type `[Review!]!`
  """
  reviews_on_restaurant: Review_ListFilter
  """
  ✨ Generated from Field `Restaurant`.`schedules_on_restaurant` of type `[Schedule!]!`
  """
  schedules_on_restaurant: Schedule_ListFilter
  """
  ✨ Generated from Field `Restaurant`.`cuisines_via_RestaurantCuisine` of type `[Cuisine!]!`
  """
  cuisines_via_RestaurantCuisine: Cuisine_ListFilter
  """
  ✨ Generated from Field `Restaurant`.`establishmentTypes_via_RestaurantType` of type `[EstablishmentType!]!`
  """
  establishmentTypes_via_RestaurantType: EstablishmentType_ListFilter
  """
  ✨ Generated from Field `Restaurant`.`users_via_Favorite` of type `[User!]!`
  """
  users_via_Favorite: User_ListFilter
  """
  ✨ Generated from Field `Restaurant`.`users_via_Review` of type `[User!]!`
  """
  users_via_Review: User_ListFilter
}
"""
✨ Generated first-row input type for table 'Restaurant'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Restaurant_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Restaurant_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Restaurant_Filter
}
"""
✨ Generated having input type for table 'Restaurant'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Restaurant_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Restaurant_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Restaurant_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Restaurant_Having!]
  """
  ✨ Generated from Field `Restaurant`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`address_count` of type `Int!`
  """
  address_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`cityId_count` of type `Int!`
  """
  cityId_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`imageUrl_count` of type `Int!`
  """
  imageUrl_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`latitude_count` of type `Int!`
  """
  latitude_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`longitude_count` of type `Int!`
  """
  longitude_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`phone_count` of type `Int!`
  """
  phone_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`status_count` of type `Int!`
  """
  status_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`website_count` of type `Int!`
  """
  website_count: Int_Filter
  """
  ✨ Generated from Field `Restaurant`.`latitude_sum` of type `Float`
  """
  latitude_sum: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`longitude_sum` of type `Float`
  """
  longitude_sum: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`latitude_avg` of type `Float`
  """
  latitude_avg: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`longitude_avg` of type `Float`
  """
  longitude_avg: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Restaurant`.`latitude_min` of type `Float`
  """
  latitude_min: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`longitude_min` of type `Float`
  """
  longitude_min: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Restaurant`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Restaurant`.`latitude_max` of type `Float`
  """
  latitude_max: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`longitude_max` of type `Float`
  """
  longitude_max: Float_Filter
  """
  ✨ Generated from Field `Restaurant`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Restaurant'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Restaurant_Key {
  """
  ✨ Generated from Field `Restaurant`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Restaurant`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Restaurant'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Restaurant_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Restaurant_Filter
}
"""
✨ Generated order input type for table 'Restaurant'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Restaurant_Order {
  """
  ✨ Generated from Field `Restaurant`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`cityId` of type `String!`
  """
  cityId: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`city` of type `City!`
  """
  city: City_Order
  """
  ✨ Generated from Field `Restaurant`.`address` of type `String!`
  """
  address: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`imageUrl` of type `String!`
  """
  imageUrl: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`latitude` of type `Float!`
  """
  latitude: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`longitude` of type `Float!`
  """
  longitude: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`phone` of type `String`
  """
  phone: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`status` of type `String!`
  """
  status: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`website` of type `String`
  """
  website: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`address_count` of type `Int!`
  """
  address_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`cityId_count` of type `Int!`
  """
  cityId_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`imageUrl_count` of type `Int!`
  """
  imageUrl_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`latitude_count` of type `Int!`
  """
  latitude_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`longitude_count` of type `Int!`
  """
  longitude_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`phone_count` of type `Int!`
  """
  phone_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`status_count` of type `Int!`
  """
  status_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`website_count` of type `Int!`
  """
  website_count: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`latitude_sum` of type `Float`
  """
  latitude_sum: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`longitude_sum` of type `Float`
  """
  longitude_sum: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`latitude_avg` of type `Float`
  """
  latitude_avg: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`longitude_avg` of type `Float`
  """
  longitude_avg: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`latitude_min` of type `Float`
  """
  latitude_min: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`longitude_min` of type `Float`
  """
  longitude_min: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`latitude_max` of type `Float`
  """
  latitude_max: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`longitude_max` of type `Float`
  """
  longitude_max: OrderDirection
  """
  ✨ Generated from Field `Restaurant`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'RestaurantCuisine'. It includes all necessary fields for creating or upserting rows into table.
"""
input RestaurantCuisine_Data {
  """
  ✨ Generated from Field `RestaurantCuisine`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `RestaurantCuisine`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RestaurantCuisine`.`cuisineId` of type `String!`
  """
  cuisineId: String
  """
  ✨ `_expr` server value variant of `cuisineId` (✨ Generated from Field `RestaurantCuisine`.`cuisineId` of type `String!`)
  """
  cuisineId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RestaurantCuisine`.`cuisine` of type `Cuisine!`
  """
  cuisine: Cuisine_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RestaurantCuisine`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Key @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'RestaurantCuisine'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input RestaurantCuisine_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [RestaurantCuisine_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: RestaurantCuisine_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [RestaurantCuisine_Filter!]
  """
  ✨ Generated from Field `RestaurantCuisine`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID_Filter
  """
  ✨ Generated from Field `RestaurantCuisine`.`cuisineId` of type `String!`
  """
  cuisineId: String_Filter
  """
  ✨ Generated from Field `RestaurantCuisine`.`cuisine` of type `Cuisine!`
  """
  cuisine: Cuisine_Filter
  """
  ✨ Generated from Field `RestaurantCuisine`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Filter
}
"""
✨ Generated first-row input type for table 'RestaurantCuisine'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input RestaurantCuisine_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [RestaurantCuisine_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: RestaurantCuisine_Filter
}
"""
✨ Generated having input type for table 'RestaurantCuisine'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input RestaurantCuisine_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [RestaurantCuisine_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: RestaurantCuisine_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [RestaurantCuisine_Having!]
  """
  ✨ Generated from Field `RestaurantCuisine`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `RestaurantCuisine`.`cuisineId_count` of type `Int!`
  """
  cuisineId_count: Int_Filter
  """
  ✨ Generated from Field `RestaurantCuisine`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: Int_Filter
}
"""
✨ Generated key input type for table 'RestaurantCuisine'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input RestaurantCuisine_Key {
  """
  ✨ Generated from Field `RestaurantCuisine`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `RestaurantCuisine`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RestaurantCuisine`.`cuisineId` of type `String!`
  """
  cuisineId: String
  """
  ✨ `_expr` server value variant of `cuisineId` (✨ Generated from Field `RestaurantCuisine`.`cuisineId` of type `String!`)
  """
  cuisineId_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'RestaurantCuisine'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input RestaurantCuisine_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: RestaurantCuisine_Filter
}
"""
✨ Generated order input type for table 'RestaurantCuisine'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input RestaurantCuisine_Order {
  """
  ✨ Generated from Field `RestaurantCuisine`.`restaurantId` of type `UUID!`
  """
  restaurantId: OrderDirection
  """
  ✨ Generated from Field `RestaurantCuisine`.`cuisineId` of type `String!`
  """
  cuisineId: OrderDirection
  """
  ✨ Generated from Field `RestaurantCuisine`.`cuisine` of type `Cuisine!`
  """
  cuisine: Cuisine_Order
  """
  ✨ Generated from Field `RestaurantCuisine`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Order
  """
  ✨ Generated from Field `RestaurantCuisine`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `RestaurantCuisine`.`cuisineId_count` of type `Int!`
  """
  cuisineId_count: OrderDirection
  """
  ✨ Generated from Field `RestaurantCuisine`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: OrderDirection
}
"""
✨ Generated data input type for table 'RestaurantType'. It includes all necessary fields for creating or upserting rows into table.
"""
input RestaurantType_Data {
  """
  ✨ Generated from Field `RestaurantType`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `RestaurantType`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RestaurantType`.`typeId` of type `String!`
  """
  typeId: String
  """
  ✨ `_expr` server value variant of `typeId` (✨ Generated from Field `RestaurantType`.`typeId` of type `String!`)
  """
  typeId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RestaurantType`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RestaurantType`.`type` of type `EstablishmentType!`
  """
  type: EstablishmentType_Key @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'RestaurantType'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input RestaurantType_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [RestaurantType_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: RestaurantType_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [RestaurantType_Filter!]
  """
  ✨ Generated from Field `RestaurantType`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID_Filter
  """
  ✨ Generated from Field `RestaurantType`.`typeId` of type `String!`
  """
  typeId: String_Filter
  """
  ✨ Generated from Field `RestaurantType`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Filter
  """
  ✨ Generated from Field `RestaurantType`.`type` of type `EstablishmentType!`
  """
  type: EstablishmentType_Filter
}
"""
✨ Generated first-row input type for table 'RestaurantType'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input RestaurantType_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [RestaurantType_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: RestaurantType_Filter
}
"""
✨ Generated having input type for table 'RestaurantType'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input RestaurantType_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [RestaurantType_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: RestaurantType_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [RestaurantType_Having!]
  """
  ✨ Generated from Field `RestaurantType`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `RestaurantType`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: Int_Filter
  """
  ✨ Generated from Field `RestaurantType`.`typeId_count` of type `Int!`
  """
  typeId_count: Int_Filter
}
"""
✨ Generated key input type for table 'RestaurantType'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input RestaurantType_Key {
  """
  ✨ Generated from Field `RestaurantType`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `RestaurantType`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RestaurantType`.`typeId` of type `String!`
  """
  typeId: String
  """
  ✨ `_expr` server value variant of `typeId` (✨ Generated from Field `RestaurantType`.`typeId` of type `String!`)
  """
  typeId_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'RestaurantType'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input RestaurantType_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: RestaurantType_Filter
}
"""
✨ Generated order input type for table 'RestaurantType'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input RestaurantType_Order {
  """
  ✨ Generated from Field `RestaurantType`.`restaurantId` of type `UUID!`
  """
  restaurantId: OrderDirection
  """
  ✨ Generated from Field `RestaurantType`.`typeId` of type `String!`
  """
  typeId: OrderDirection
  """
  ✨ Generated from Field `RestaurantType`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Order
  """
  ✨ Generated from Field `RestaurantType`.`type` of type `EstablishmentType!`
  """
  type: EstablishmentType_Order
  """
  ✨ Generated from Field `RestaurantType`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `RestaurantType`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: OrderDirection
  """
  ✨ Generated from Field `RestaurantType`.`typeId_count` of type `Int!`
  """
  typeId_count: OrderDirection
}
"""
✨ Generated data input type for table 'Review'. It includes all necessary fields for creating or upserting rows into table.
"""
input Review_Data {
  """
  ✨ Generated from Field `Review`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Review`.`userId` of type `String!`)
  """
  userId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Review`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `Review`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Review`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Review`.`user` of type `User!`
  """
  user: User_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Review`.`comment` of type `String!`
  """
  comment: String
  """
  ✨ `_expr` server value variant of `comment` (✨ Generated from Field `Review`.`comment` of type `String!`)
  """
  comment_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Review`.`rating` of type `Int!`
  """
  rating: Int
  """
  ✨ `_expr` server value variant of `rating` (✨ Generated from Field `Review`.`rating` of type `Int!`)
  """
  rating_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `rating` (✨ Generated from Field `Review`.`rating` of type `Int!`)
  """
  rating_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Review`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `Review`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `Review`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `Review`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Review'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Review_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Review_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Review_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Review_Filter!]
  """
  ✨ Generated from Field `Review`.`userId` of type `String!`
  """
  userId: String_Filter
  """
  ✨ Generated from Field `Review`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID_Filter
  """
  ✨ Generated from Field `Review`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Filter
  """
  ✨ Generated from Field `Review`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Review`.`comment` of type `String!`
  """
  comment: String_Filter
  """
  ✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Review`.`rating` of type `Int!`
  """
  rating: Int_Filter
  """
  ✨ Generated from Field `Review`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'Review'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Review_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Review_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Review_Filter
}
"""
✨ Generated having input type for table 'Review'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Review_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Review_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Review_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Review_Having!]
  """
  ✨ Generated from Field `Review`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Review`.`comment_count` of type `Int!`
  """
  comment_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`rating_count` of type `Int!`
  """
  rating_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `Review`.`rating_sum` of type `Int`
  """
  rating_sum: Int_Filter
  """
  ✨ Generated from Field `Review`.`rating_avg` of type `Float`
  """
  rating_avg: Float_Filter
  """
  ✨ Generated from Field `Review`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Review`.`rating_min` of type `Int`
  """
  rating_min: Int_Filter
  """
  ✨ Generated from Field `Review`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Review`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Review`.`rating_max` of type `Int`
  """
  rating_max: Int_Filter
  """
  ✨ Generated from Field `Review`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Review'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Review_Key {
  """
  ✨ Generated from Field `Review`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `Review`.`userId` of type `String!`)
  """
  userId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Review`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `Review`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Review'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Review_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Review_Filter
}
"""
✨ Generated order input type for table 'Review'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Review_Order {
  """
  ✨ Generated from Field `Review`.`userId` of type `String!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `Review`.`restaurantId` of type `UUID!`
  """
  restaurantId: OrderDirection
  """
  ✨ Generated from Field `Review`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Order
  """
  ✨ Generated from Field `Review`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Review`.`comment` of type `String!`
  """
  comment: OrderDirection
  """
  ✨ Generated from Field `Review`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating` of type `Int!`
  """
  rating: OrderDirection
  """
  ✨ Generated from Field `Review`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `Review`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Review`.`comment_count` of type `Int!`
  """
  comment_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_count` of type `Int!`
  """
  rating_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_sum` of type `Int`
  """
  rating_sum: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_avg` of type `Float`
  """
  rating_avg: OrderDirection
  """
  ✨ Generated from Field `Review`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_min` of type `Int`
  """
  rating_min: OrderDirection
  """
  ✨ Generated from Field `Review`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `Review`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Review`.`rating_max` of type `Int`
  """
  rating_max: OrderDirection
  """
  ✨ Generated from Field `Review`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Schedule'. It includes all necessary fields for creating or upserting rows into table.
"""
input Schedule_Data {
  """
  ✨ Generated from Field `Schedule`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `Schedule`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Schedule`.`day` of type `Int!`
  """
  day: Int
  """
  ✨ `_expr` server value variant of `day` (✨ Generated from Field `Schedule`.`day` of type `Int!`)
  """
  day_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `day` (✨ Generated from Field `Schedule`.`day` of type `Int!`)
  """
  day_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Schedule`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Schedule`.`closed` of type `Boolean!`
  """
  closed: Boolean
  """
  ✨ `_expr` server value variant of `closed` (✨ Generated from Field `Schedule`.`closed` of type `Boolean!`)
  """
  closed_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Schedule`.`closes` of type `String`
  """
  closes: String
  """
  ✨ `_expr` server value variant of `closes` (✨ Generated from Field `Schedule`.`closes` of type `String`)
  """
  closes_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Schedule`.`opens` of type `String`
  """
  opens: String
  """
  ✨ `_expr` server value variant of `opens` (✨ Generated from Field `Schedule`.`opens` of type `String`)
  """
  opens_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Schedule'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Schedule_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Schedule_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Schedule_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Schedule_Filter!]
  """
  ✨ Generated from Field `Schedule`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID_Filter
  """
  ✨ Generated from Field `Schedule`.`day` of type `Int!`
  """
  day: Int_Filter
  """
  ✨ Generated from Field `Schedule`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Filter
  """
  ✨ Generated from Field `Schedule`.`closed` of type `Boolean!`
  """
  closed: Boolean_Filter
  """
  ✨ Generated from Field `Schedule`.`closes` of type `String`
  """
  closes: String_Filter
  """
  ✨ Generated from Field `Schedule`.`opens` of type `String`
  """
  opens: String_Filter
}
"""
✨ Generated first-row input type for table 'Schedule'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Schedule_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Schedule_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Schedule_Filter
}
"""
✨ Generated having input type for table 'Schedule'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Schedule_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Schedule_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Schedule_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Schedule_Having!]
  """
  ✨ Generated from Field `Schedule`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Schedule`.`closed_count` of type `Int!`
  """
  closed_count: Int_Filter
  """
  ✨ Generated from Field `Schedule`.`closes_count` of type `Int!`
  """
  closes_count: Int_Filter
  """
  ✨ Generated from Field `Schedule`.`day_count` of type `Int!`
  """
  day_count: Int_Filter
  """
  ✨ Generated from Field `Schedule`.`opens_count` of type `Int!`
  """
  opens_count: Int_Filter
  """
  ✨ Generated from Field `Schedule`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: Int_Filter
  """
  ✨ Generated from Field `Schedule`.`day_sum` of type `Int`
  """
  day_sum: Int_Filter
  """
  ✨ Generated from Field `Schedule`.`day_avg` of type `Float`
  """
  day_avg: Float_Filter
  """
  ✨ Generated from Field `Schedule`.`day_min` of type `Int`
  """
  day_min: Int_Filter
  """
  ✨ Generated from Field `Schedule`.`day_max` of type `Int`
  """
  day_max: Int_Filter
}
"""
✨ Generated key input type for table 'Schedule'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Schedule_Key {
  """
  ✨ Generated from Field `Schedule`.`restaurantId` of type `UUID!`
  """
  restaurantId: UUID
  """
  ✨ `_expr` server value variant of `restaurantId` (✨ Generated from Field `Schedule`.`restaurantId` of type `UUID!`)
  """
  restaurantId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Schedule`.`day` of type `Int!`
  """
  day: Int
  """
  ✨ `_expr` server value variant of `day` (✨ Generated from Field `Schedule`.`day` of type `Int!`)
  """
  day_expr: Int_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Schedule'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Schedule_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Schedule_Filter
}
"""
✨ Generated order input type for table 'Schedule'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Schedule_Order {
  """
  ✨ Generated from Field `Schedule`.`restaurantId` of type `UUID!`
  """
  restaurantId: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`day` of type `Int!`
  """
  day: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`restaurant` of type `Restaurant!`
  """
  restaurant: Restaurant_Order
  """
  ✨ Generated from Field `Schedule`.`closed` of type `Boolean!`
  """
  closed: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`closes` of type `String`
  """
  closes: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`opens` of type `String`
  """
  opens: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`closed_count` of type `Int!`
  """
  closed_count: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`closes_count` of type `Int!`
  """
  closes_count: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`day_count` of type `Int!`
  """
  day_count: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`opens_count` of type `Int!`
  """
  opens_count: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`restaurantId_count` of type `Int!`
  """
  restaurantId_count: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`day_sum` of type `Int`
  """
  day_sum: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`day_avg` of type `Float`
  """
  day_avg: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`day_min` of type `Int`
  """
  day_min: OrderDirection
  """
  ✨ Generated from Field `Schedule`.`day_max` of type `Int`
  """
  day_max: OrderDirection
}
"""
✨ Generated data input type for table 'User'. It includes all necessary fields for creating or upserting rows into table.
"""
input User_Data {
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr @fdc_forbiddenInVariables
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `User`.`email` of type `String!`)
  """
  email_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`role` of type `String!`
  """
  role: String
  """
  ✨ `_expr` server value variant of `role` (✨ Generated from Field `User`.`role` of type `String!`)
  """
  role_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`username` of type `String!`
  """
  username: String
  """
  ✨ `_expr` server value variant of `username` (✨ Generated from Field `User`.`username` of type `String!`)
  """
  username_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `User`.`favorites_on_user` of type `[Favorite!]!`
  """
  favorites_on_user: [Favorite_Data!]
  """
  ✨ Generated from Field `User`.`reviews_on_user` of type `[Review!]!`
  """
  reviews_on_user: [Review_Data!]
}
"""
✨ Generated filter input type for table 'User'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [User_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: User_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [User_Filter!]
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: String_Filter
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `User`.`role` of type `String!`
  """
  role: String_Filter
  """
  ✨ Generated from Field `User`.`username` of type `String!`
  """
  username: String_Filter
  """
  ✨ Generated from Field `User`.`favorites_on_user` of type `[Favorite!]!`
  """
  favorites_on_user: Favorite_ListFilter
  """
  ✨ Generated from Field `User`.`reviews_on_user` of type `[Review!]!`
  """
  reviews_on_user: Review_ListFilter
  """
  ✨ Generated from Field `User`.`restaurants_via_Favorite` of type `[Restaurant!]!`
  """
  restaurants_via_Favorite: Restaurant_ListFilter
  """
  ✨ Generated from Field `User`.`restaurants_via_Review` of type `[Restaurant!]!`
  """
  restaurants_via_Review: Restaurant_ListFilter
}
"""
✨ Generated first-row input type for table 'User'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input User_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [User_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: User_Filter
}
"""
✨ Generated having input type for table 'User'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [User_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: User_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [User_Having!]
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `User`.`role_count` of type `Int!`
  """
  role_count: Int_Filter
  """
  ✨ Generated from Field `User`.`username_count` of type `Int!`
  """
  username_count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'User'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input User_Key {
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: String
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `User`.`id` of type `String!`)
  """
  id_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'User'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input User_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: User_Filter
}
"""
✨ Generated order input type for table 'User'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input User_Order {
  """
  ✨ Generated from Field `User`.`id` of type `String!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `User`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `User`.`role` of type `String!`
  """
  role: OrderDirection
  """
  ✨ Generated from Field `User`.`username` of type `String!`
  """
  username: OrderDirection
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `User`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `User`.`role_count` of type `Int!`
  """
  role_count: OrderDirection
  """
  ✨ Generated from Field `User`.`username_count` of type `Int!`
  """
  username_count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
